#!/usr/bin/env python3
"""Build the human source map from the canonical JSON records."""
import argparse
from collections import Counter
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
LABELS = {'content_reviewed': '正文已读', 'partial_content_reviewed': '选段已读',
          'metadata_verified': '仅书目核验', 'unverified': '未核验'}
CATEGORIES = [
    ('专业书籍', {'book'}), ('标准与规范', {'standard'}),
    ('学术论文', {'paper'}), ('机构研究与权威网站', {'technical_report', 'official_technical_article', 'handbook'}),
    ('厂商手册、应用与参考板', {'datasheet', 'application_note', 'reference_design'}),
    ('开源项目', {'open_source_project', 'open_hardware'})]

def render():
    records = [source for path in sorted((ROOT/'references/sources').glob('*.json'))
               for source in json.loads(path.read_text(encoding='utf-8'))]
    counts = Counter(source['access_status'] for source in records)
    lines = ['# 来源地图', '', '<!-- Generated by scripts/build_source_map.py; edit sources/*.json. -->', '',
             '此页由结构化登记生成。收录不等于全文阅读；“选段已读”包括合法样章/预览，需打开记录确认具体范围。', '',
             f'共 **{len(records)}** 项独立登记：' + '，'.join(f'{LABELS[s]} {counts[s]}' for s in LABELS) + '。', '',
             '所有摘要为原创整理。未在本地复现文献实验；标准网页/目录不提供未取得的条款依据。完整作者、版本、DOI/ISBN、定位、限制和核验日期见 [sources/](sources/)。', '']
    known = set()
    for heading, kinds in CATEGORIES:
        selected = [source for source in records if source['kind'] in kinds]
        known.update(kinds)
        if not selected:
            continue
        lines += [f'## {heading}（{len(selected)}）', '', '| ID | 原始资料 | 发布者 | 阅读状态 |', '|---|---|---|---|']
        for source in sorted(selected, key=lambda record: record['id']):
            title = source['title'].replace('|', '\\|').replace('[', '\\[').replace(']', '\\]')
            publisher = source['publisher'].replace('|', '\\|')
            lines.append(f'| {source["id"]} | [{title}]({source["url"]}) | {publisher} | {LABELS[source["access_status"]]} |')
        lines.append('')
    unknown = sorted(set(source['kind'] for source in records)-known)
    if unknown:
        raise ValueError(f'Add source map categories for: {unknown}')
    return '\n'.join(lines)+'\n'

if __name__ == '__main__':
    sys.stdout.reconfigure(encoding='utf-8')
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    target = ROOT/'references/source-map.md'
    content = render()
    if args.check:
        if not target.exists() or target.read_text(encoding='utf-8') != content:
            raise SystemExit('Source map is stale. Run python scripts/build_source_map.py')
        print('Source map is current.')
    else:
        target.write_text(content, encoding='utf-8')
        print('Updated references/source-map.md')
